### ISSUE TITLE
Message error and autogpt close

### ISSUE THREAD

**Issue by Snyhel** [Wladastic/Auto-GPT-Telegram-Plugin#11]
Hello i got this message : 

Waiting for response on Telegram chat...
Sending message to Telegram.. 
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<TelegramUtils._send_message() done, defined at plugins\Auto-GPT-Telegram.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\telegram_chat.py:97> exception=TypeError("object list can't be used in 'await' expression")>
Traceback (most recent call last):
  File "plugins\Auto-GPT-Telegram.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\telegram_chat.py", line 101, in _send_message
    bot = await self.get_bot(self)
  File "plugins\Auto-GPT-Telegram.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\telegram_chat.py", line 59, in get_bot
    commands = await bot.get_my_commands()
TypeError: object list can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Snyhe\Desktop\Nouveau dossier\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Snyhe\Desktop\Nouveau dossier\Auto-GPT\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\Users\Snyhe\Desktop\Nouveau dossier\Auto-GPT\autogpt\main.py", line 135, in run_auto_gpt
    ai_config = construct_main_ai_config()
  File "C:\Users\Snyhe\Desktop\Nouveau dossier\Auto-GPT\autogpt\prompts\prompt.py", line 105, in construct_main_ai_config
    should_continue = clean_input(
  File "C:\Users\Snyhe\Desktop\Nouveau dossier\Auto-GPT\autogpt\utils.py", line 29, in clean_input
    plugin_response = plugin.user_input(user_input=prompt)
  File "plugins\Auto-GPT-Telegram.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\__init__.py", line 260, in user_input
  File "plugins\Auto-GPT-Telegram.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\telegram_chat.py", line 193, in ask_user
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Snyhe\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "plugins\Auto-GPT-Telegram.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\telegram_chat.py", line 116, in ask_user_async
  File "plugins\Auto-GPT-Telegram.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\telegram_chat.py", line 159, in _poll_updates
  File "plugins\Auto-GPT-Telegram.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\telegram_chat.py", line 59, in get_bot
TypeError: object list can't be used in 'await' expression

**Comment by Wladastic** [comment]
It seems like autogpt passed some object instead of a string?

**Comment by Wladastic** [comment]
How did you configure it?
If get bot fails it looks like it has something to do with the api key

**Comment by soufianeelmouatassim** [comment]
same here
the token is correct

**Comment by Wladastic** [comment]
I cannot reproduce your bug.
What version of autogpt are you using?

**Comment by soufianeelmouatassim** [comment]
AutoGPT 0.3.0, Git installation. The other extensions work perfectly but not the telegram bot.

**Comment by Wladastic** [comment]
Please uninstall telegram and install python-telegram-bot package.

**Comment by soufianeelmouatassim** [comment]
Thankyou! FIXED!!

python -m pip install --upgrade pip
pip list --outdated
showed may outdated packages 📦
I used awk to extract the package names from the output of pip list --outdated, and then xargs is used to execute pip install -U for each package.
pip list --outdated | awk '{print $1}' | xargs -n1 pip install -U
