### ISSUE TITLE
ImportError: cannot import name 'Bot' from 'telegram'

### ISSUE THREAD

**Issue by crack00r** [Wladastic/Auto-GPT-Telegram-Plugin#12]
C:\Users\Manuel\Desktop\GPT\Auto-GPT>run.bat
All packages are installed.
NEWS:  Welcome to Auto-GPT!
NEWS:  Below you'll find the latest Auto-GPT News and updates regarding features!
NEWS:  If you don't wish to see this message, you can run Auto-GPT with the --skip-news flag.
NEWS:
NEWS:  Website and Documentation Site 📰📖
NEWS:  Check out https://agpt.co, the official news & updates site for Auto-GPT!
NEWS:  The documentation also has a place here, at https://docs.agpt.co
NEWS:
NEWS:  🚀 v0.3.0 Release 🚀
NEWS:  Over a week and 275 pull requests have passed since v0.2.2, and we are happy to announce
NEWS:  the release of v0.3.0! From now on, we will be focusing on major improvements rather
NEWS:  than bugfixes, as we feel stability has reached a reasonable level. Most remaining
NEWS:  issues relate to limitations in prompt generation and the memory system, which will be
NEWS:  the focus of our efforts for the next release.
NEWS:
NEWS:  Highlights and notable changes in this release:
NEWS:
NEWS:  Plugin support 🔌
NEWS:  Auto-GPT now has support for plugins! With plugins, you can extend Auto-GPT's abilities,
NEWS:  adding support for third-party services and more.
NEWS:  See https://github.com/Significant-Gravitas/Auto-GPT-Plugins for instructions and available plugins.
NEWS:
NEWS:  Changes to Docker configuration 🐋
NEWS:  The workdir has been changed from /home/appuser to /app.
NEWS:  Be sure to update any volume mounts accordingly!
NEWS:
NEWS:  ⚠️ Command `send_tweet` is DEPRECATED, and will be removed in v0.4.0 ⚠️
NEWS:  Twitter functionality (and more) is now covered by plugins, see [Plugin support 🔌]
NEWS:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Manuel\Desktop\GPT\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\Desktop\GPT\Auto-GPT\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\Users\Manuel\Desktop\GPT\Auto-GPT\autogpt\main.py", line 118, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\Desktop\GPT\Auto-GPT\autogpt\plugins.py", line 219, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen zipimport>", line 301, in load_module
  File "plugins\Auto-GPT-Telegram-Plugin-master.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\__init__.py", line 11, in <module>
  File "plugins\Auto-GPT-Telegram-Plugin-master.zip\Auto-GPT-Telegram-Plugin-master\src\telegram_plugin\telegram_chat.py", line 4, in <module>
ImportError: cannot import name 'Bot' from 'telegram' (C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\telegram\__init__.py)
Drücken Sie eine beliebige Taste . . .

**Comment by crack00r** [comment]
C:\Users\Manuel\Desktop\GPT\Auto-GPT>pip3 install telegram
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: telegram in c:\users\manuel\appdata\roaming\python\python311\site-packages (0.0.1)

C:\Users\Manuel\Desktop\GPT\Auto-GPT>

**Comment by Wladastic** [comment]
python -m autogpt --install-plugin-deps
