### ISSUE TITLE
message is too long

### ISSUE THREAD

**Issue by soyelmismo** [Wladastic/Auto-GPT-Telegram-Plugin#9]
```
NEXT ACTION:  COMMAND = google ARGUMENTS = {'query': 'lista de los 15 virreyes y de cuando a cuando gobernaron'}

 Confirm: /yes     Decline: /no

-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 

Sending message to Telegram.. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 157, in run_auto_gpt
    agent.start_interaction_loop()
  File "/app/autogpt/agent/agent.py", line 247, in start_interaction_loop
    logger.typewriter_log("SYSTEM: ", Fore.YELLOW, result)
  File "/app/autogpt/logs.py", line 87, in typewriter_log
    plugin.report(f"{title}. {content}")
  File "plugins/Auto-GPT-Telegram.zip/Auto-GPT-Telegram-Plugin-master/src/telegram_plugin/__init__.py", line 268, in report
  File "plugins/Auto-GPT-Telegram.zip/Auto-GPT-Telegram-Plugin-master/src/telegram_plugin/telegram_chat.py", line 85, in send_message
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "plugins/Auto-GPT-Telegram.zip/Auto-GPT-Telegram-Plugin-master/src/telegram_plugin/telegram_chat.py", line 101, in _send_message
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 368, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 797, in send_message
    return await self._send_message(
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 549, in _send_message
    result = await self._post(
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 456, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 487, in _do_post
    return await request.post(
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 328, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long

```

**Comment by soyelmismo** [comment]
this is causing the container stops

**Comment by Wladastic** [comment]
Already fixed around the same time :)
